AllenDang/giu

- Widgets.go
- examples/plot/main.go
- go.sum
This patch only wraps the PlotLines widget from imgui, but the histogram
and other plotting widgets could be wrapped also.
This also adds an example in examples/plot showing both g.PlotLines()
and g.PlotLinesV().
Future work: the imgui plotting widget is a little limited, it would be
nice for GIU to support a more robust plotting system. This could
perhaps be done from scratch based on a Canvas widget, possibly by
writing a back-end for gonum/plot.
> add wrapper for imgui PlotLines widget

- Widgets.go
- examples/plot/main.go
Rather than requiring the user to import imgui for the Vec2 type, we now
just accept with width and height directly.
I think it's OK to use `imgui.Vec2` internally still, but I can remove the `graphSize` field and replace it with two floats if @AllenDang thinks that would be better. Let me know and I will patch it.
> Make PlotLinesV consistent with other functions

- Widgets.go
I require the use of ImageButtonV and have implemented a Widget that uses it.
I have some uncertainly with how I've done it. `ImageButtonVWidget` seems awkward as the type, as no other widgets have a verbose version. Would it make sense to adjust `ImageButtonWidget` to contain all of the fields I have placed in the verbose widget and have the regular widget properly populate these fields (similar to how imgui.ImageButton/imgui.ImageButtonV work)? This would probably fit with the general style better.
Additionally, I am also uncertain about the use of image.Point and color.RGBA but this seemed better than using imgui.Vec2/Vec4 directly (unless I'm mistaken). I've used the ToVec2/ToVec4Color utility functions in Utils.go for converting between these two types.
Using the widget is as below …
> ImageButtonV Widget

- Canvas.go
- imgui/DrawList.go
- imgui/DrawListWrapper.cpp
- imgui/DrawListWrapper.h
I need to draw images with color and alpha modulation, and as such, have implemented the AddImageV func to the Canvas.
I was uncertain if Canvas should have a different AddImage func, such as `AddColoredImage` or otherwise, so I opted to go with a "verbose" version of AddImage.
Let me know if I need to make any changes or if this approach is wrong.
> Canvas.AddImageV and DrawList.AddImageV

- Events.go
- Flags.go
- imgui/imgui.go
- imgui/imguiWrapper.cpp
- imgui/imguiWrapper.h
I needed to detect if a window was focused and hovered so I implemented the bindings for both IsWindowFocused and IsWindowHovered, as well as IsWindowCollapsed for completeness.
For additional completeness, I have also added all of the hovered and focused flags to Flags.go, as it seemed better than just picking the ones I needed.
To note, one of the applications of this is for a KeyBinds/KeyBind widget that adheres to giu's layout->build style.
> IsWindowCollapsed, IsWindowFocused, IsWindowHovered

- examples/plot/main.go
This is an insignificant change, but it reduces type conversions, and makes the `loop` function a few lines shorter, while still grouping relevant things together and keeping to "idiomatic go" style.
> Minor examples/plot refactoring.

- MainThread.go
There is no functionality changes, though I find this solution shorter and cleaner. See previous PR #65.
This implementation was inspired by
https://github.com/duffn/gophercon2018#rethinking-classical-concurrency-patterns.
Please let me know if you don't like the lines joined, and I'll split them. Please don't hesitate to reject the PR in case you think it isn't worth the change.
> No extra go routines for MainThread.

- MasterWindow.go
These two methods can be used to move a borderless window.
> Add GetPos and SetPos for MasterWindow

- go.mod
- go.sum
- imgui/RendererOpenGL3.go
- imgui/TextureID.go
- imgui/imconfig.h
- imgui/imguiWrapperTypes.h
These changes remove the unsafe pointer arithmetic problems, thereby
allowing us to actually run giu-based programs with the "-race" flag.
There are still issues that exist in relation to creating textures,
as is made apparent by running any example with the "-race" flag
enabled. There likely needs to be locking/unlocking on either texture
access or wherever texture creation/access is intended. Ideally one
would set up some sort of channel communication for loading textures
and notifying the render thread that they are ready for use.
> Switch to neclepsio gl fork; Change TextureID types

- MasterWindow.go
Current approach won't work if you have any OpenGL operation outside of a separate Framebuffer. The problem is that `r.PreRender()` clears GL canvas right after `w.updateFunc()` which is actually an application loop. I've changed the order to comply.
> Change render order for MasterWindow

- Texture.go
This method is required in all cases where you need to pass OpenGL texture  (or raw pointer) to any of Image widget.
> Add method to convert imgui.Texture to Texture

- Widgets.go
- imgui/Vectors.go
Builder pattern is already used to create widgets. Yet, when you need additional, but optional arguments you should create an extended `*V` method with all args (and everthing will be required to pass). At least that is how it's done for now. PR shows a proper way to solve that problem. For now only for `ImageWidget` (since it's needed for me), but if you're OK with that approach, I'll add more methods like that for other widgets I'll meet in the future.
Also two additional methods were added for Vec2 and Vec4 structs to set their values.
> Extend ImageWidget with additional builder methods

- imgui/imgui.go
This solves issue #151 where a C dependency of imgui was missing during the build for windows.
Building this example now works: https://github.com/AllenDang/giu/blob/master/examples/helloworld/helloworld.go
> Fix: imm32 ldflags while building imgui

- FontAtlasProsessor.go
this fixes #212 
Sadly I got some strange issues with google-noto (on my other machine) but I added `FreeSanse.ttf` it doesn't look so bad
> fonts: add gnu-free/FreeSans.ttf for linux

- README.md
I've tested giu on macOS Big Sur (x64) and Windows 11(x64). Both work with giu no problem.
> Update with working platforms

- Texture.go
- Utils.go
- Widgets.go
- textures.go: use image.Image instead of image.RGBA in arg to NewTextureFromRGBA
- use autoid for imagebuttonwithrgba
- create ImageToRgba method
it should be easier to use
> widgets: replace image.RGBA with image.Image interface:

- .gitignore
hi,
it is a kind of pain when you see n-time :grinning:
```console
3 files changed, 28 insertions(+)
create mode 100644 .Layout.go.swp
```
> gitignore: add vim cache files (swp)

- Utils.go
```golang
size := imgui.CalcTextSize(text, false, 0)
```
@allenDang why default value of `hideAfterDoubleHash` is  `false`?
> utils: add CalcTextSizeV

- Texture.go
- Widgets.go
- examples/canvas/canvas.go
- examples/texturefiltering/texturefiltering.go
because of the issues with loading textures in mainthread it is better to allow the giu to call a callback when it is done with loading the texture.
change type of NewTextureFromRgba: func(imag.Image) (*Texture, error) -> func(image.Image, func(*Texture)).
this should fix #316
> breaking: Textures: change the type of NewTextureFromRgba

- Layout.go
- StackWidget.go
- examples/extrawidgets/extrawidgets.go
Hi there!
here is a stack widget, which was mentioned in https://github.com/AllenDang/giu/pull/300#issuecomment-910105402
stack widget ensures if build methods of all widgets are called, but only the `visible` layout is rendered (visible)
usage: g.Stock(0, g.Label("I'm a visible label"), g.Label("I'm invisible label"))
> add StackWidget

- CodeEditor.go
fix bug, when calling giu.CodeEditor() directly in a Layout caused recreating imgui.TextEditor each time
> codeEditor: store editor in state

- Alignment.go
- examples/align/align.go
(*AlignSetter).Build() is much shorter now
> alignment: refactoirng build method

- CodeEditor.go
- examples/codeeditor/codeeditor.go
> breaking: CodeEditor(): remove `title` argument.

- Alignment.go
this fixes #425 however it has one weakness: the user can still interract with widget that's width we're measuring.
> alignsetter: change id of widget inside of GetWidgetWidth method

- README.md
Copying the example code does not work unless that ``` , nil ``` is removed
Original 
```golang
wnd := g.NewMasterWindow("Hello world", 400, 200, g.MasterWindowFlagsNotResizable, nil)
```
New 
```golang
wnd := g.NewMasterWindow("Hello world", 400, 200, g.MasterWindowFlagsNotResizable)
```
> Update README.md to fix example

- FontAtlasProsessor.go
By default, `sans` is a general alias for some configured sans-serif font. That guarantees, that at least _some_ font is initialized.
Else, some code relying on initialized default fonts will fail. An example is `example/markdown`
> Set a sane fallback font on Linux.

- ImageWidgets.go
- Markdown.go
- go.mod
- go.sum
This reduces the dependency complexity, given that the usage is very simple. Reduces the example application size for image and markdown by ~1MB each.
> Replace resty dependency by standard http library.

- ExtraWidgets.go
Add two further configuration options for the `DatePicker`:
- Allow to specify a format in which the current date should be displayed
- Allow to specify the first day of the week: As a German, seeing calendars start on Sunday is always _very_ confusing :)
```go
g.DatePicker("datePicker", &guiCfg.Date).
Format("02.01.2006").StartOfWeek(time.Monday).
Size(120),
```
> Enhance DatePicker

- ExtraWidgets.go
My PR #438 broke selecting a date in the DatePicker, because I misread the format string.
Fixed it and replaced it by directly constructing a `time.Date` object without parsing a created string.
> [DatePicker] Fix selecting a date

- Context.go
- MasterWindow.go
- Texture.go
- examples/loadimage/loadimage.go
- go.mod
- go.sum
this should clearify the panic, that appears when user tries to load texture befor calling (*MasterWindow).Run
> textures: check if the main loop is runing before loading texture

- .github/workflows/build.yml
- build_windows.go
fix #452 
@AllenDang idk how to add another ldflags like `-s -w -H=windowsgui` as only `-static` works and another one causes build crash :-(
> package: add appripiate ld flag for static linking on for windows

- README.md
I did a typo in package name and it didn't worked well.
> readme: fix incorrect package name for fedora's mingw

- ImageWidgets.go
Added check if the current window is focused to OnClick detection of ImageWidget.
Without this ImageWidgets will also detect OnClick if there is a click on a overlapping window on top. Feel free to reject the PR, if this is desired.
There currenlty is a workaround like:
```go
giu.Custom(func() {
img := giu.Image(texture)
if giu.IsWindowFocused(0) {
img = img.OnClick(onClick)
}
img.Build()
})
```
> Small bugfix for ImageWidget OnClick detection

- InputHandler.go
- InputHandler_test.go
- Keycode.go
- MasterWindow.go
- examples/issue-501/main.go
> input handler: add possibility to set additional input callback

- ClickableWidgets.go
- CodeEditor.go
- Context.go
- Context_test.go
- EventHandler.go
- ExtraWidgets.go
- ImageWidgets.go
- MemoryEditor.go
- Msgbox.go
- ProgressIndicator.go
- SplitLayout.go
- TextWidgets.go
- Window.go
Hi @AllenDang @gucio321 I saw #517 and since I've been using generics a lot recently, I figured I'd try my hand at making the changes.
The `GetState` and `SetState` functions still exist on the `context` struct for backwards compatibility, but there are now generic versions of them.
I've also updated the "internal" code to use the generic version instead.
I've kept the assert still for `GetState` to catch/prevent any mixing up of types.
The "reason" behind `[T any, genericDisposable[T]]` is explained [here](https://go.googlesource.com/proposal/+/HEAD/design/43651-type-parameters.md#pointer-method-example)
Although I'm using it to directly call `Dispose`, it helps enforce the Disposable interface and it's also needed to have the return type as a pointer of the generic type.
Feel free to …
> Added generic functions for context management

- FontAtlasProsessor.go
Add Chinese fonts on linux.
In China, wqy-* fonts is very popular among Linux users.
SourceHanSansCN maybe default Chinese font on Manjaro Linux.
> add Chinese fonts on linux

- Widgets.go
- examples/widgets/widgets.go
It looks like shortcut property for the MenuItem is currently always an empty string. I have updated it so it can be passed and rendered. Also updated one of the examples so it can be demonstrated.
> add shortcut property to MenuItemWidget

- TextWidgets.go
Because the step size was hard coded to 0. The step size was disabled and step buttons did not appear. Added functions (and variables) to set the step sizes, so that this functionality of the input widgets can be used in giu as well.
> Widgets: Add step size support to InputFloat- and InputInt-text widgets. 

- StyleSetter.go
It is intened to be used in #533 for setting main CSS tag on MasterWindow (see #533) but this is a separated change that could be useful not depending on CSS stuff
> Style setter: separate Push() and Pop() methods

- Alignment.go
- examples/align/align.go
Hi!
I've enhanced my AlignSetter so it works prefect now :smile:
update: #596
> Alignment updates

- .github/workflows/golangci-lint.yaml
- use macOS for runner to avoid extra updating/downloading
- use the go.mod file to determine go version
> {ci} Clean up golangci job

- EventHandler.go
- Events.go
- Keycode.go
- Widgets.go
- Events.go: wrapps cimgui events detection
- EventHandler.go: giu version of event handler
- Keycode.go: now contains a few more things, e.g. HoveredFlags
- add (*ContextMenu).MouseButton(...); fix #609
> docking: migrate events system:

- .golangci.yml
- `gofumpt` conflicts with `wsl`
- `gci` conflicts with `goimports`
`gofumpt` and `gci` don't add that much that isn't already covered by `wsl` and  `goimports` anyways.
Also reorder file to be more logical & clean up unused settings.
> Linting: Turn off conflicting linters

- ClickableWidgets.go
- CodeEditor.go
- Context.go
- Context_test.go
- EventHandler.go
- ExtraWidgets.go
- FontAtlasProsessor.go
- ImageWidgets.go
- MemoryEditor.go
- Msgbox.go
- ProgressIndicator.go
- SplitLayout.go
- TextWidgets.go
- Window.go
govet was complaining about copying these because they contain mutex locks which should never be copied.
"copylocks: call of GetState[teststate] copies lock value"
Fixes #588
> govet: Use pointers for Context and FontAtlas

- TableWidgets.go
> table widget: render table with no rows anyway

- README.md
@AllenDang let me know what do you think about my (maybe too radical) changes in documentation (epecially wiki/discussion/readme).
In case of this PR:
I think our readme should clearly point where we hold our documentation so that we can point it at any time in issues.
> readme: add paragraph about documentation

- examples/codeeditor/codeeditor.go
it is important to call NewMasterWindow before doing anything in giu (since we don't use init funcs anymore)
fix #689
> examples: fix crash in codeeditor demo

- ImageWidgets.go
> image with rgba: fix rgba bug

- mainthread_all.go
- mainthread_windows.go
in reference to https://github.com/AllenDang/giu/issues/735#issuecomment-1951419027 we have no mainthread library that works on windows. Due to this fact I think that the best solution is to disable mainthread completely for winows until we find some working solution.
I'll create an issue about this as soon as this change is merged to master
> mainthread: disable on windows

- TextWidgets.go
fix https://github.com/AllenDang/giu/issues/781
> label: use TextUnformatted

- Canvas.go
- ClickableWidgets.go
- Events.go
- Flags.go
- ImageWidgets.go
- MasterWindow.go
- Plot.go
- Texture.go
- Widgets.go
- go.mod
- go.sum
> update cimgui-go version

- FontAtlasProsessor.go
- Keycode.go
@gucio321 Can you help to test whether giu will still crash on linux? I add the fonts.Clear() back in order to display Chinese characters.
> Fix panic and font alats

- .github/workflows/golangci-lint.yaml
- .golangci.yml
- Alignment.go
- Canvas.go
- CodeEditor.go
- Context.go
- ExtraWidgets.go
- Flags.go
- FontAtlasProsessor.go
- InputHandler_test.go
- Layout_test.go
- Markdown.go
- MasterWindow.go
- Plot.go
- ProgressIndicator.go
- SliderWidgets.go
- StyleIDs.go
- StyleIDs_string.go
- StyleIDs_string2enum.go
- Utils.go
- Widgets.go
- cmd/gmdeploy/main.go
now linter is back on after #628
> Linter: update and fix issues

- Alignment.go
- ClickableWidgets.go
- CodeEditor.go
- Context.go
- EventHandler.go
- ExtraWidgets.go
- ImageWidgets.go
- SliderWidgets.go
- SplitLayout.go
- TableWidgets.go
- TextWidgets.go
- Widgets.go
this allows to disable GenAutoID
> add GenAutoID to Context

- Alignment.go
- ClickableWidgets.go
- CodeEditor.go
- Context.go
- Context_test.go
- EventHandler.go
- ExtraWidgets.go
- ImageWidgets.go
- SliderWidgets.go
- SplitLayout.go
- TableWidgets.go
- TextWidgets.go
- Utils.go
- Widgets.go
- Window.go
@AllenDang I did something like this, is it ok?
> add a special type for IDs

- Plot.go
- examples/plot/main.go
progress on #765 
This is not complete unfortunately, but I don't have much time right now.
I can come back in a couple of weeks. but this may be useful for now.
> Implement plot 2nd and 3rd axis

- MasterWindow.go
In a new API, ScaleAllSizes neds to be called only once
I moved it to the beginning of the programm in NewMasterWindow.
This fixes #810
> master window: fix DPI scaling

- ImageWidgets.go
you can now do .Size(0,0) and the image takes its original size
> Added the option for image to take its original size

- TableWidgets.go
Discussion here:
https://github.com/AllenDang/giu/discussions/829
The SimpleHeader() idea in the first post is too inflexible. This pull request is for the NoHeader() idea from the second post.
> Add NoHeader() to TableWidget

- MasterWindow.go
The effect is particularly visible in the drawing of tables during window resizing
beforeRender() now called from sizeChange() in MasterWindow.go. this is because beforeRender() is never called when resizing a GLFW window
context.CleanSlate() moved from afterRender() to beginning of render() function. this is because afterRender(), like beforeRender() is never called when resizing
it would be ineffective to call CleanSlate() from the sizeChange() function. calling CleanSlate() at the beginning of the render() has the same affect as calling it from afterRender() in all situations.
> Fixed issue with resizing events in GLFW master window

- Context.go
> Context: fix invalid reference to not-existing variable

- Alignment.go
The current right-aligned element will extend slightly beyond the main interface. And when the element is in a container, there is a deviation from the starting position between center and right alignment. Just add the offset at the starting position in the original code and remove the calculation of the border.
before:
after:
> fix bug of center and right alignment

- README.md
Adds the new standard go docs badge:
[![Go Reference](https://pkg.go.dev/badge/github.com/AllenDang/giu.svg)](https://pkg.go.dev/github.com/AllenDang/giu)
Looks better than this, which seems like it's supposed to render something but it's broken?:
[![Godoc Card](https://camo.githubusercontent.com/fd3cd5d5f44237541b35fcfdcba2fd4466a60c12/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f476f646f632d7265666572656e63652d626c75652e737667)](https://pkg.go.dev/github.com/AllenDang/giu?tab=doc)
> readme: Add fancy docs badge

- examples/dragdrop/dragdrop.go
There were 3 problems:
- call to SetDragDropPayload declared data_size always as 0
- null chceck in DragDropTarget checked only if returned payload isn't nil but didn't if CData isn't (cimgui-go changs - generally should be fixed in cimgui-go somehow)
- there was also a small issue in result decoding as the label presented pointer address and not its value
resolve #832
> examples/dragdrop: fix crash

- MasterWindow.go
Update MasterWindow witj GLFWWindowsFlagsVisible access
It is used by cases where we really don't want any native window decoration.
It usually implies this MasterWindow preambule
```
imgui.CreateContext()
io := imgui.CurrentIO()
io.SetConfigViewportsNoAutoMerge(true)
io.SetConfigViewportsNoDefaultParent(true)
wnd := g.NewMasterWindow("Client", 1, 1,g.MasterWindowFlagsHidden|g.MasterWindowFlagsFrameless)
wnd.Run(loop)
```
> Add MasterWindowFlagsHidden

- MasterWindow.go
Reverts AllenDang/giu#831
Reasons:
- causes #862 (giant problems with performence and overall giu functionalities)
- I see absolutly no reason why beforeRender should be called in OnSizeChange (After fixing state mechanism, calling beforeRender in OnSizeChange doesn't help) - I'll open an issue for the problem with hube list example..
close #863, close #862
> Revert "Fixed issue with resizing events in GLFW master window"

- ReflectiveBoundTexture.go
- examples/paint/canvas.go
* custom texture binding for Reflective to avoid double free
* and race condition fix in appending draw commands for paint example
> ReflectiveBoundTexture: Custom texture binding 

- mainthread_windows.go
fixes #881 close 764 with a note that this commit may have some unexpected consequences in which case it could be reverted.
> mainthread: lock main os threa on Windows

- ExtraWidgets.go
- Gizmo.go
- MasterWindow.go
- Utils.go
- examples/gizmo/main.go
- go.mod
- go.sum
cimgui-go in version v1.1.0 added ImGuizmo.
Giu can also implement it in some nice way (by nice I mean not how cimgui-go does it)
> add Gizmo widget and example for it

- Flags.go
- MasterWindow.go
- Plot.go
- StyleIDs.go
- StyleSetter.go
- go.mod
- go.sum
in the latest commit in cimgui-go we've updated some function names.
I introduce them in giu asap to avoid loses of my time later.
Applied with this:
```go
sed -i -e 's/implot\.Plot/implot\./g' -e 's/imnodes\.ImNodes/imnodes\./g' *go
```
> Upgrade cimgui go (introduce func names changes)

- README.md
TDM-GCC is https://github.com/jmeubank/tdm-gcc.
The current version of gcc provided by the project is 10.3.0. According to https://github.com/jmeubank/tdm-gcc/issues/68 I think the project was discontinued.
According to https://github.com/AllenDang/giu/issues/911 we are forced to stop recommending tdm-gcc for giu.
> readme: do not recommend tdm-gcc anymore

- ClickableWidgets.go
I've just noticed that 2 ImageButton's with the same texture are conflicting items for imgui. Now ImageButton auto-generates and ID and adds ID method if someone wants to set the ID manually
> Clickable widget: push auto ids

- SplitLayout.go
- examples/splitter/splitter.go
until now the only and default behaviour was counting from left/top. I've added possibility to interpret sashPos from right/bottom or as percent (%) of availableRegion
> feat(SplitLayout): support different sashPos interpretations

- ClickableWidgets.go
I have no idea why someone would create this button with its default size but doing that caused immediate programm crash (0-size assertion)
Generally the default size could be any random number different from 0 but -1 (aka Auto) sounds reasonable
> fix(InvisibleButton): Set default size to -1, -1

- examples/transparent/transparent.go
> Transparent example: makes frameless windows movable

- Flags.go
- Plot.go
- examples/plot/main.go
This feature was missing and allows us to properly display time on the x axis again.
> Add Plot Scale fields for setting time/log/symlog on x, y, y2, and y3 axis

- MasterWindow.go
I think this would be an easy fix for #773. You can simple set the style for the MasterWindow using `SetStyle`, thus reusing the code for the StyleSetter. If there is a style set, it just uses the `Push` and `Pop` methods of that StyleSetter instead of the default theme.
> Set style for MasterWindow | #773

- StyleSetter.go
- StyleSetter_test.go
this method allows to add another StyleSetter on top of any other one.
Will be useful when adding styles on top of default master window style
> style setter: add Add method

- SliderWidgets.go
- Widgets.go
- examples/loadimageAdvanced/loadimageAdvanced.go
- examples/widgets/widgets.go
- move DragInt to SliderWidgets.go
- **BREAKING** remove non-mandatory arguments form the main widget's creator. Add setters instead. `s/DragInt(\(.*\),\(.*\),\(.*\),\(.*\))/DragInt(\2)\.Label(\1)\.MinValue(\3).MaxValue(\4)/g` should do the migration
- added `DragFloatWidget`
> Drag widgets rework

- TableWidgets.go
Fixes a SEGV when run on tables without the IsSortable Flag.
> sortable-table: only run sort on sortable tables

- ExtraWidgets.go
This PR contains the code that I've been using to build over a range from a map (resolves #973), though I doubt that it is the best implementation; I didn't want to change library code when I originally wrote this.
A good alternative that I have not personally explored may be to make the regular `RangeBuilder` function generic enough to take maps as well as slices.
> Add rangebuilder variant that accepts maps

- FontAtlasProsessor.go
new instance of fontInfo structure was created after font being scaled This caused font not being found.
fix #759
> fix(FontAtlas): copy scaled font size before modifying it

- Widgets.go
- examples/widgets/widgets.go
In examples/imguidemo, there is a combo box with a filter. It sadly doesn't seem to exist currently, creating quite a false-promise. So, I went to the original imgui repo and took the [code from there](https://github.com/ocornut/imgui/blob/5679de60c567fc62c091004ee80a738757e6d3b6/imgui_demo.cpp#L1318-L1339) to create a `Filter` method on the `ComboWidget`, specifying if there should be a TextFilter when opening it.
> Added Filter to ComboWidget

- .gitignore
- MasterWindow.go
- examples/sortable-table/main.go
See #987.
On a `MasterWindow`, you can call `SetUserFile` to specify the path to a user .ini file (for saving subwindow locations, table column widths, etc).
`examples/sortable-table` has an example.
> Making the user .ini file optional

- .github/ISSUE_TEMPLATE/bug_report.yml
I've noticed some reports do not include valid version information "master" (current default) does not say anything useful. The new template, asks user to issue git rev-parse and post commit ID or tag name.
> github/issue_template: improve bug report template

- CSS.go
- Context_test.go
- FontAtlasProsessor.go
- MasterWindow.go
- Style.go
- StyleSetter.go
- examples/markdown/markdown.go
- examples/multiplefonts/multiplefonts.go
after #1028 Font atlas should be completely reworked (or maybe even removed (?)
This is WIP Pull Request.
- Remove eintire `(*FontInfo).size` mechanism (ncluding `SetSize`) method
- Remove `size` parameter from all the SetDefaultFont*, AddFont* methods
> BREAKING Font Atlas size handling rework

- Canvas.go
- ClickableWidgets.go
- CodeEditor.go
- Context.go
- FontAtlasProsessor.go
- Markdown.go
- Plot.go
- Popups.go
- ProgressIndicator.go
- SliderWidgets.go
- TableWidgets.go
- TextWidgets.go
- Widgets.go
- Window.go
- examples/paint/toolbar.go
since imgui 1.92, passing glyph ranges is no longer needed.
fix #1035
> Font atlas: remove glyph ranges
