examples/update/update.go
You don't have a contributing file so I'm not sure if you're looking for contributions, but while browsing I noticed a minor typo here and figured I would submit a PR.
=> examples/update: Fix minor typo

imgui/ColorEditFlags.go, imgui/ColorPickerFlags.go
=> Run gofmt on whole code-base

MasterWindow.go, examples/transparent/transparent.go, imgui/PlatformGlfw.go
With the support of frameless and transparent, we can create windows like this.
=> Add frameless and transparent window support

examples/multiwindow/multiwindow.go
small tweak to show how to add the "x" close button on window 2
=> add close button to window 2

imgui/IO.go, imgui/IOWrapper.cpp, imgui/IOWrapper.h, imgui/WrapperConverter.cpp, imgui/WrapperConverter.h, imgui/imguiWrapperTypes.h
I've implemented `IO.GetMouseWheelDelta` and `IO.GetMouseWheelHDelta` accessors. This involved adding wrapper types for float32 among other things.
=> IO MouseWheelDelta and MouseWheelHDelta access

Context.go
It is safe in go to delete (and add) values from the map we iterate
over.
=> Cleanup context state in one loop.

go.mod, go.sum, imgui/RendererOpenGL3.go, imgui/TextureID.go, imgui/imconfig.h, imgui/imguiWrapperTypes.h
=> Revert "Switch to neclepsio gl fork; Change TextureID types"

imgui/RendererOpenGL3.go
This PR refers to the issue https://github.com/inkyblackness/imgui-go/issues/42
In a nutshell, the copypasted OpenGL renderer uses `TextureDataAlpha8()` to generate fonts atlas. This results in behaviour, which could be seen in the issue (monochrome images, when using `imgui.Image`). It's motivated by memory usage "optimization". Yet, that solution follows to several drawbacks. First, in 32bit `uintptr` doesn't has 32 more free bits. Yet, it's the only way to handle image for now. The argument itself is pretty poor, because the memory win, even in 64bit apps, is somewhere between 1.5-2 Mb. Even with Chinese glyphs it doesn't count on modern PCs. Imho, it's an edge case to handle it generally. Currently it only leads to confusion. (I've spent a whole day to find that specific problem.) …
=> Generate fonts atlas with TextureDataRGBA32

imgui/imgui.go, imgui/imguiWrapper.cpp, imgui/imguiWrapper.h
=> Add imgui scroll functions

Widgets.go
Hi there,
In my opinion setting width for sliders might be useful, however I'm not sure about setting height. Should it also be an argument to `Size`?
=> slider float: added onChange callback; sliders: added Size (and width)

README.md
I've added simple build instructions for linux, tested on live debian bullseye installation, and inside of a debian:sid docker container.
=> Added Linux build instruction

Flags.go, Widgets.go, examples/widgets/widgets.go
Hi there,
I added implementation of imgui.SetColor4V
=> widgets: add setColor widget

FontAtlasProsessor.go
Hi,
In some complex project I was getting `Concurrent map read and write` panic
=> FontAtlas: fix `concurrent map read and write` panic in tStr

Window.go, examples/bringToFront/bringToFront.go
implements part of https://github.com/ianling/giu/commit/2420694cee09f95f514b9dccc62536533665570d
=> add BringToFront method and example

Context.go, InputHandler.go, Keycode.go, MasterWindow.go, Window.go, examples/focused/main.go, examples/keyboardShortcuts/keyboardShortcuts.go
Hi,
It could be nice to support keyboard shortcuts inside of giu.
=> Input manager

cmd/gmdeploy/assets.go, cmd/gmdeploy/main.go
Hi there
I added compilation instruction for linuxes
also a minor improvement: current os is now displayed as default in help
=> Gmdeploy: add linux case

Widgets.go, examples/loadimage/loadimage.go
Hi there,
this might be useful
=> widgets/Image: add onClick callback

README.md
I know you're from China (I am too 😄 ), so there are some English mistakes. My pull fixes spelling and grammar mistakes in the README.
=> Fix spelling and grammar, make more clear

Widgets.go
=> widgets: add ImageButtonWithRgba

MasterWindow.go, examples/loadimage/loadimage.go
(instead of []image.Image
add example for SetIcon (in loadimage))
=> masterWindow: SetIcon argument is now ...image.Image

Msgbox.go, examples/msgbox/msgbox.go
- refactor msgbox to use chain of methods
- add msgbox example
=> Msgbox refactor

CodeEditor.go, examples/codeeditor/codeeditor.go
hi there,
I looked into codeEditor.go file and example and noticed, that the editor doesn't looks like another widget so I decided to improve it.
=> Code editor refactor

Context_test.go, go.mod
=> unittests: add unittest for context.go

Direction.go, Events.go
=> standarize enums

EventHandler.go, examples/widgets/widgets.go
related with https://github.com/AllenDang/giu/issues/303#issuecomment-910248822
=> eventHandler: add OnActivate and OnDezactivate methods

Widgets.go
add (*InvisibleButton).ID(...) use auto id generator by default
=> breaking: remove id arg from InvisibleButton

Widgets.go
hi there,
it may be useful to do just
`giu.Label("this is some int: %d and string %s", 5, "string")`
instead of using fmt.sprintf
`giu.Label(fmt.Sprintf("this is some int: %d and string %s", 5, "string"))`
or maybe I should add `Labelf`?
=> widgets: add formatting possibility to some widgets

Alignment.go, examples/align/align.go
align setter is able to center/align to right some widgets.
it is some type of "BETA" solution and may contain lot of bugs
@AllenDang what do you think about this?
=> add AlignSetter

README.md, Widgets.go
Hi there!
I took a look on giu's go report card and noticed this:
So I decided to take a closer look on DatePickerWidget.
Here is a couple of refactors on this widgets which may make the widget code easier to read.
=> date picker refactor

README.md, Widgets.go
ops, a small typo in some of previous PRs.
=> Hotfix: fix BulletTextf

Widgets.go, examples/extrawidgets/extrawidgets.go, examples/helloworld/helloworld.go, examples/widgets/widgets.go
hi,
here is a cupple of small changes, code simplifies done in Widgets.go
CHANGES:
=> widgets refactors

Alignment.go, Layout.go, examples/align/align.go
Hi!
in this PR I fixed one of bugs, I mentioned in Alignment.go
Also, I added the Range feature for Layout type.
this method does similar to sync.Map.Range - it ranges over the layout widgets. if another layout found (or the widget implements Range method) it calls w.Range.
=> Alignment refactoring

README.md
Fixed various spelling and grammar in the README.md file.
=> Fixed spelling and grammar.

Widgets.go
@AllenDang should I add tStrID to trim ##.* part of id to avoid registering unnecessary characters in font atlas?
=> widgets: fix auto id generator bug (fix #346)

Alignment.go
=> bugfix: fix bug when align to center offset was calculated incorrectly

.gitignore
https://github.com/AllenDang/giu/pull/162#issuecomment-927257590
=> gitignore: add vendor dir

Flags.go, Style.go, examples/setstyle/setstyle.go
=> StyleSetter: add SetFontSize

Style.go
=> style setter: fix bug, when pushing nil font caused crash

Markdown.go, examples/markdown/markdown.go, go.mod, go.sum
needs to wait until https://github.com/AllenDang/imgui-go/pull/10
Features:
- images from URL
- image effects
- uv0, uv1
- tint color
- border color
=> missing features of imgui markdown

.github/workflows/golangci-lint.yaml, .golangci.yml, Canvas.go, FontAtlasProsessor.go, ImageWidgets.go, Markdown.go, Msgbox.go, Utils.go, cmd/gmdeploy/main.go, cmd/gmdeploy/utils.go
- update golangci-lint's version used by workflow
- fix some lint errors
- comment out `revive` to fix github workflow
=> update linter to v1.44.0

Alignment.go, examples/align/align.go
well, this should be better than current AlignSetter, however I leave it there because maybe Dear Imgui's `measure widget width` issue gets fixed in some point in future ;-)
=> alignment: add manual alignment feature

.github/ISSUE_TEMPLATE/bug_report.yml
v0.5.6 isn't latest anymore :tada:
=> update issue template for bug report

.github/workflows/golangci-lint.yaml
_I need to open this before it is ready because golangci-lint github action doesn't run on local branches (only master and pull requests)_
=> fixes in linter and linter's workflow

README.md
I faced again the issue I've reproted myself :grinning: https://github.com/AllenDang/giu/issues/449
=> readme: add cross-building instruction for linux

.github/workflows/build.yml, .github/workflows/coverage.yaml, .github/workflows/golangci-lint.yaml, .gitignore, ClickableWidgets.go, Context.go, ExtraWidgets.go, FontAtlasProsessor.go, SliderWidgets.go, Style.go, TextWidgets.go, Texture.go, Utils.go, Widgets.go, go.mod, go.sum
@AllenDang go 1.18 is there!
here is changelog: https://go.dev/doc/go1.18
that new feature - generics - seems to be interessting. I need to investigate it as I don't understand how does it work yet.
=> go mod: update to go 1.18

SplitLayout.go, examples/markdown/markdown.go, examples/splitter/splitter.go
user could change sashPos value as well as read it
fix #485
=> SplitLayout: make `sashPos` argument a pointer 

SplitLayout.go
Now working as expected, details to the Problem u find here https://github.com/AllenDang/giu/issues/496
=> SplitLayout (DirectionHorizontal == Vertical?) & (DirectionVertical == Horizontal?)

ImageWidgets.go
**NOTE:** introduce some API changes!
fix #490
=> image widget: fix bug, when Uv was procesed incorrectly

Canvas.go, ClickableWidgets.go, CodeEditor.go, ExtraWidgets.go, FontAtlasProsessor.go, Markdown.go, Plot.go, Popups.go, ProgressIndicator.go, SliderWidgets.go, TableWidgets.go, TextWidgets.go, Widgets.go, Window.go
=> font atlas: expose tStr and related

.github/workflows/build.yml, .github/workflows/golangci-lint.yaml
Hi!
I'm trying to fix workflows as they all fails now...
=> Fix workflows

examples/fps/main.go
=> examples: add FPS calculation programm

Alignment.go, Canvas.go, ClickableWidgets.go, CodeEditor.go, Context_test.go, Events.go, Flags.go, FontAtlasProsessor.go, ImageWidgets.go, InputHandler.go, InputHandler_test.go, Layout.go, ListClipper.go, MasterWindow.go, MemoryEditor.go, Msgbox.go, Popups.go, README.md, SliderWidgets.go, SplitLayout.go, StackWidget.go, TextWidgets.go, Widgets.go, Window.go, cmd/gmdeploy/main.go, examples/align/align.go, examples/customwidget/customwidget.go
(...and a couple of grammar issues)
=> Fix spelling

Canvas.go, go.mod, go.sum
this allows user to assign a custom draw list to canvas, and use giu-based methods
=> Plot: add possibility to use PlotDrawList

Canvas.go, ExtraWidgets.go
A couple of the remaining lint issues.
After #608, #611, and this one are merged, I have one more PR which fixes the rest...
=> Linting: Small fixes

CSS.go
Error texts were also slightly modified so we could just use one error instead of defining several.
Complexity was fixed by replacing a 2-iteration loop with one function call (removing spaces from a string).
=> Linter: Fix dynamic errors and function complexity

StyleSetter.go
=> style setter: fix invalid behaviour of StyleSetter in RowWidget

Context.go, Context_test.go, ImageWidgets.go, MasterWindow.go, Msgbox.go, ProgressIndicator.go, Utils.go
Hi!
while working on one of my projects and dealing `-race`, I got the following issues that _probably_ are related to giu nor my project :smile:
=> context: fix concurrency issues

TextWidgets.go
=> Input text autocomplete fixes

ExtraWidgets.go
I confused directions :smile: sorry
=> hotfix for #662: fix bug when splitter was moved incorrectly

ExtraWidgets.go
=> splitter: fix mouse cursor types

TextWidgets.go
Hi
As I started to use this feature, I concluded that it lacks some essential features that I'm going to add here.
First of all I add highlight and possibility to chose another item from list
=> Autocomplete improvement

TextWidgets.go
=> input text: call onChange when autocomplete

ImageWidgets.go
=> ImageWidget: fix OnClick method

Utils.go, Utils_test.go
as a side-effect I've added an unittest for UintToColor
fix #715
=> utils: fix ColorToUint

MasterWindow.go
=> master rwindow: fix bug with segfault when resizing window with MenuBar

Canvas.go, examples/canvas/canvas.go
=> Image quad

StyleIDs.go, StyleIDs_string.go, StyleIDs_string2enum.go
=> add missing style ids

ExtraWidgets.go, examples/widgets/widgets.go
don't require id argument in ListBox method, use AutoID instead
=> ListBoxWidget: fix ID handling

ExtraWidgets.go
- redesign month/day switcher
- add user translations of built-in labels
=> date picker updates

Plot.go
This is disabled since migration -now I've figured out what it should be in the new cimgui-go
=> plot: add LineXY

Plot.go
Whn I was reading the code (and TODOs ;-) ) I noticed that my ticks setup was completely wrong
Now it should work as expectred
=> plot: fix axis ticks

go.mod, go.sum
should fix windows issues
Also, I have to save 83% of my battery so I let github test this :D
=> go: update cimgui to latest master

TableWidgets.go
=> Check if no Columns or Rows were sent to TableWidget

MasterWindow.go
=> master window: add SetFPS method

Widgets.go
=> combo: allow empty string

ClickableWidgets.go, Direction.go, Flags.go, MasterWindow.go, Plot.go, Style.go, go.mod, go.sum
=> fix constants

ExtraWidgets.go
it was so annoying to convert single widget to Layout
now, because Layout implements Widget, this change is backwor dcompatible
=> ConditionWIdget: use Widget instad of Layout

Alignment.go, ClickableWidgets.go, CodeEditor.go, Context.go, EventHandler.go, ExtraWidgets.go, ImageWidgets.go, SliderWidgets.go, SplitLayout.go, TableWidgets.go, TextWidgets.go, Widgets.go
=> Revert "add GenAutoID to Context"

Context.go, Window.go
make it less possible to change some IDs and cause strange layout behaviours
Sometimes, when there were nested layouts and some of them were dynamically generated depending on other widgets, it caused some strange UI behaviours
=> contedt: redesign Auto ID system

go.mod, go.sum
update cimgui-go to latest version #827
=> update cimgui-go to latest version

StyleIDs_string.go
=> re-run go generate

ImageWidgets.go
Without the whole reflectiveBoundTexture. I'll rename and separate the other PR.
@gucio321 you were so close...
=> Fix ImageWithRGBAWidget filling GPU Memory

Flags.go
=> Add WindowFlagsNoDocking

go.mod
=> go mod: update go version bugfix number

SplitLayout.go
=> fix(SplitLayout): height of 2nd child in V-split

ImageWidgets.go
=> Fix image widget click event detection

CodeEditor.go, examples/codeeditor/codeeditor.go, go.mod, go.sum
cimgui-go added ImGuiCodeEditor (or at least some part of it).
We can reenable it here.
=> Reenable code editor

Markdown.go, MasterWindow.go, examples/markdown/markdown.go, go.mod, go.sum
_I'm completely aware of panic appearing when running examples/markdown and I'm working on it_
=> Add markdown widget

Widgets.go
=> widgets: add ID() method to the ComboWidget

examples/setstyle/setstyle.go
Adding an example in examples/setstyle for #943.
=> Example for setting MasterWindow.SetStyle

MasterWindow.go, StyleSetter.go
=> Default Theme: convert to StyleSetter

Widgets.go, examples/widgets/widgets.go
=> TabItem: add possibility to attach an EventHandler

Widgets.go
also detect change event
ref #955
=> widgets/DragIntWidget: add OnChange method

TableWidgets.go, examples/sortable-table/main.go
=> Table sort

FontAtlasProsessor.go
=> font atlas: add possibility to disable RegisterString

go.mod, go.sum
=> go(deps): upgrade go-css

Popups.go
When `OpenPopup` is called from a `MenuItem`, the popup does not open (#986).
This is being fixed by creating a state in `OpenPopup`, which then gets read when building the popup itself, ensuring that it always gets open.
=> Shifting popup open time | #986
